### ISSUE TITLE
about the selected compounds in Figure 7.D. of paper

### ISSUE THREAD

**Issue by MachineGUN001** [tiantz17/MolSHAP#1]
hi, 

Thanks so much for providing such an interesting and helpful approach. For utilizing the molshap method, picking out three compounds is mentioned in the article. Could you please provide explanation what criteria or method was used to select these three compounds? Is the activity listed in the article the result after the actual bioassay?

Additionally, what is the ranking of compounds in the generated - opt. csv file based on? Is it uncertainy SD?

many thanks,

Sh-Y

**Comment by tiantz17** [comment]
Hi Sh-Y, 

Thanks for your interest!

The optimized compounds were first filtered based on the predicted activity (pIC50 > 6 as in Fig. 7C). Then, we obtained as more as compounds to ensure diversity (916 compounds here). Note that the generated molecules were not experimentally validated at this moment, even may not synthesized. After that, we compared the structures of 916 optimized compounds with 132 compounds in the test set, the latter were synthesized and evaluated in bioassay. This resulted in three overlapped compounds shown in Fig. 7D. And then we checked their activity and found that they exhibited good potency. In other words, we did not know their real activity before we select the three compounds.

As for the generated *opt.csv, the compounds were not ranked. You can manually sort them by the predicted activities. I will add the sorting to the code. Thanks for your questions.

Best, 
Tingzhong

**Comment by MachineGUN001** [comment]
thanks for your kind explanation.
