### ISSUE TITLE
Documentation: Your publication

### ISSUE THREAD

**Issue by metma99** [tiantz17/MolSHAP#2]
Hello:
Fist of all, thank you for  making MolSHAP available t the community.
I am very interested in your work and would like to read the original publication.
Unfortunately, this article is behind a paywall.
Is there a way you can provide me with a preprint?
Many thanks in advance,
Markus

**Comment by tiantz17** [comment]
Hi,
Thanks for your interest!
Below please find the latest version of our paper before publication.
[MolSHAP-Journal-revise2-clean.pdf](https://github.com/tiantz17/MolSHAP/files/12592768/MolSHAP-Journal-revise2-clean.pdf)
Best,
Tingzhong

**Comment by metma99** [comment]
Thank you very much,Markus On Sep 12, 2023, at 7:29 PM, Tingzhong Tian ***@***.***> wrote:﻿
Hi,
Thanks for your interest!
Below please find the latest version of our paper before publication.
MolSHAP-Journal-revise2-clean.pdf
Best,
Tingzhong
